# Generated by Django 6.0.4 on 2026-04-28 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abakozi',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('izina', models.CharField(max_length=100)),
                ('akazi', models.CharField(max_length=100)),
                ('arakora', models.BooleanField(default=True)),
                ('itariki', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Umushahara',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('itariki', models.DateTimeField()),
                ('umushahara', models.IntegerField()),
                ('umukozi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.abakozi')),
            ],
        ),
    ]
