# Generated by Django 6.0.4 on 2026-04-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abakozi',
            name='izina',
        ),
        migrations.AddField(
            model_name='abakozi',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='abakozi',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
