# Generated by Django 6.0.4 on 2026-04-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_abakozi_izina_abakozi_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abakozi',
            name='Id',
        ),
        migrations.AlterField(
            model_name='umushahara',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='abakozi',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
