# Generated by Django 6.0.4 on 2026-04-29 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_abakozi_id_alter_umushahara_id_abakozi_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='umushahara',
            name='igihe',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='times', to='employees.abakozi'),
        ),
    ]
