# Generated by Django 6.0.4 on 2026-04-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_umushahara_igihe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umushahara',
            name='igihe',
            field=models.DateField(default=True),
        ),
    ]
