# Generated by Django 6.0.4 on 2026-04-29 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_umushahara_igihe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='umushahara',
            name='itariki',
        ),
    ]
