# Generated by Django 6.0.4 on 2026-04-29 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_remove_umushahara_itariki'),
    ]

    operations = [
        migrations.AddField(
            model_name='umushahara',
            name='akaz',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='times', to='employees.abakozi'),
        ),
    ]
