# Generated by Django 6.0.4 on 2026-04-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_umushahara_akaz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='umushahara',
            name='akaz',
        ),
        migrations.AlterField(
            model_name='umushahara',
            name='igihe',
            field=models.DateField(),
        ),
    ]
